from flask_sqlalchemy import SQLAlchemy

TESTCONFIG='adextee'
MERCHANT_ID='UUFHFIUEWHGVSABFF'
DEBUG=True
ADMIN_EMAIL='zainabkappo@yahoo.com'
FLASK_RUN_PORT = 8090
SECRET_KEY='470safe'


SQLALCHEMY_DATABASE_URI=''
SQLALCHEMY_TRACK_MODIFICATIONS=False
