"""empty message

Revision ID: acd2296683b8
Revises: 
Create Date: 2021-12-21 13:37:06.356749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acd2296683b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.add_column('insurance', sa.Column('insurance_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('insurance', sa.Column('insurance_car_id', sa.Integer(), nullable=False))
    op.drop_column('insurance', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('insurance', 'insurance_car_id')
    op.drop_column('insurance', 'insurance_id')
    op.create_table('services',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('service_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('service_price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
